name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - release/development
trigger:
  branches:
    include:
      - release/development

jobs:
  - job: build_and_deploy_job
    displayName: Build and Deploy Job
    condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
    pool: linux-agent
    variables:
      - group: io2-frontend-variable-group
    steps:
      - checkout: self
        submodules: true

      - task: Npm@1
        displayName: 'npm install'
        inputs:
          command: 'install'
          workingDir: '$(System.DefaultWorkingDirectory)'

      - task: Npm@1
        displayName: 'npm build'
        inputs:
          command: 'custom'
          customCommand: 'run build'
          workingDir: '$(System.DefaultWorkingDirectory)'

      - task: AzureStaticWebApp@0
        displayName: 'Deploy to Azure Static Web App'
        inputs:
          azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
          app_location: '$(System.DefaultWorkingDirectory)'
          output_location: '.next'
